In [3]:
import random
import pandas as pd
import numpy as np

random.seed(42) #Semilla para reproducibilidad del experimento
sucursal_norte = pd.DataFrame({
    "Laptop" : [random.randint(1,20) for _ in range(4)],
    "Teclado" : [random.randint(1,20) for _ in range(4)],
    "Tablet" : [random.randint(1,20) for _ in range(4)],
    "Audifonos" : [random.randint(1,20) for _ in range(4)],
})
sucursal_sur = pd.DataFrame({
    "Laptop" : [random.randint(1,20) for _ in range(4)],
    "Teclado" : [random.randint(1,20) for _ in range(4)],
    "Tablet" : [random.randint(1,20) for _ in range(4)],
    "Audifonos" : [random.randint(1,20) for _ in range(4)],
})
display("Sucursal norte")
display(sucursal_norte)
display("Sucursal sur")
display(sucursal_sur)

'Sucursal norte'

   Laptop  Teclado  Tablet  Audifonos
0       4        8       3          1
1       1        5      19          3
2       9        4      14          7
3       8       18       2          8

'Sucursal sur'

   Laptop  Teclado  Tablet  Audifonos
0      17        7      15          6
1      20       18      19         14
2       1       14       9         11
3      18        8       1          9

In [9]:
ventas = pd.concat([sucursal_norte, sucursal_sur])
display(ventas)

print(ventas.index)
print(ventas.columns)
print(ventas.shape)

   Laptop  Teclado  Tablet  Audifonos
0       4        8       3          1
1       1        5      19          3
2       9        4      14          7
3       8       18       2          8
0      17        7      15          6
1      20       18      19         14
2       1       14       9         11
3      18        8       1          9

Index([0, 1, 2, 3, 0, 1, 2, 3], dtype='int64')
Index(['Laptop', 'Teclado', 'Tablet', 'Audifonos'], dtype='object')
(8, 4)

In [13]:
#Concatear dos dataframes a lo largo dek índice, ignorando los valores del índice de origen
ventas = pd.concat([sucursal_norte, sucursal_sur], ignore_index= True)
display(ventas)

ventas.loc[:,'Tablet']
ventas['Audifonos']

   Laptop  Teclado  Tablet  Audifonos
0       4        8       3          1
1       1        5      19          3
2       9        4      14          7
3       8       18       2          8
4      17        7      15          6
5      20       18      19         14
6       1       14       9         11
7      18        8       1          9

0     1
1     3
2     7
3     8
4     6
5    14
6    11
7     9
Name: Audifonos, dtype: int64

## Concatenar dataframes con columnas diferentes

In [16]:
random.seed(42) #Semilla para reproducibilidad del experimento
sucursal_norte = pd.DataFrame({
    "Laptop" : [random.randint(1,20) for _ in range(3)],
    "Teclado" : [random.randint(1,20) for _ in range(3)],
    "Tablet" : [random.randint(1,20) for _ in range(3)],
    "Audifonos" : [random.randint(1,20) for _ in range(3)],
})
sucursal_sur = pd.DataFrame({
    "Laptop" : [random.randint(1,20) for _ in range(4)],
    "Mouse" : [random.randint(1,20) for _ in range(4)],
    "HDMI" : [random.randint(1,20) for _ in range(4)],
    "MicroSD" : [random.randint(1,20) for _ in range(4)],
})
display("Sucursal norte")
display(sucursal_norte)
display("Sucursal sur")
display(sucursal_sur)

'Sucursal norte'

   Laptop  Teclado  Tablet  Audifonos
0       4        8       4         19
1       1        8      18         14
2       9        5       3          2

'Sucursal sur'

   Laptop  Mouse  HDMI  MicroSD
0       1     17     7       15
1       3     20    18       19
2       7      1    14        9
3       8     18     8        1

In [ ]:
ventas = pd.concat([sucursal_norte, sucursal_sur], ignore_index= True)
ventas
#Une los datos a lo largo del índice y los datos que faltan se rellenan con NaN

   Laptop  Teclado  Tablet  Audifonos  Mouse  HDMI  MicroSD
0       4      8.0     4.0       19.0    NaN   NaN      NaN
1       1      8.0    18.0       14.0    NaN   NaN      NaN
2       9      5.0     3.0        2.0    NaN   NaN      NaN
3       1      NaN     NaN        NaN   17.0   7.0     15.0
4       3      NaN     NaN        NaN   20.0  18.0     19.0
5       7      NaN     NaN        NaN    1.0  14.0      9.0
6       8      NaN     NaN        NaN   18.0   8.0      1.0

In [18]:
ventas = pd.concat([sucursal_norte, sucursal_sur], axis = 1)
ventas

   Laptop  Teclado  Tablet  Audifonos  Laptop  Mouse  HDMI  MicroSD
0     4.0      8.0     4.0       19.0       1     17     7       15
1     1.0      8.0    18.0       14.0       3     20    18       19
2     9.0      5.0     3.0        2.0       7      1    14        9
3     NaN      NaN     NaN        NaN       8     18     8        1

In [ ]:
print(sucursal_norte)
print(sucursal_sur)
#Conservar las filas con índices coincidentes
ventas = pd.concat([sucursal_norte, sucursal_sur], axis = 1, join = 'inner')
print(ventas)

   Laptop  Teclado  Tablet  Audifonos
0       4        8       4         19
1       1        8      18         14
2       9        5       3          2
   Laptop  Mouse  HDMI  MicroSD
0       1     17     7       15
1       3     20    18       19
2       7      1    14        9
3       8     18     8        1
   Laptop  Teclado  Tablet  Audifonos  Laptop  Mouse  HDMI  MicroSD
0       4        8       4         19       1     17     7       15
1       1        8      18         14       3     20    18       19
2       9        5       3          2       7      1    14        9

In [25]:
sucursal_A = pd.DataFrame({
    "Producto" : ["Laptop", "Tablet", "Smartphone"],
    "Ventas_A" : [25, 85, 31]
})
sucursal_B = pd.DataFrame({
    "Producto" : ["Laptop", "Tablet", "Smartwatch"],
    "Ventas_B" : [42, 23, 40]
})
print(sucursal_A)
print(sucursal_B)

     Producto  Ventas_A
0      Laptop        25
1      Tablet        85
2  Smartphone        31
     Producto  Ventas_B
0      Laptop        42
1      Tablet        23
2  Smartwatch        40

In [ ]:
ventas = pd.concat([sucursal_A.set_index('Producto'), sucursal_B.set_index('Producto')], axis = 1, join = 'outer')
ventas = ventas.fillna(0)
#ventas = ventas.astype(int)
print(ventas)

            Ventas_A  Ventas_B
Producto
Laptop            25        42
Tablet            85        23
Smartphone        31         0
Smartwatch         0        40

In [30]:
rainbows = []
for x in range(5):
    df = pd.DataFrame({
        'red': [random.randint(1,20)],
        'orange': [random.randint(1,20)],
        'yellow': [random.randint(1,20)],
        'green': [random.randint(1,20)],
        'blue': [random.randint(1,20)],
        'indigo': [random.randint(1,20)],
        'violet': [random.randint(1,20)]})
    rainbows.append(df)
rainbows

[   red  orange  yellow  green  blue  indigo  violet
 0    9      15      12      6    12      12       7,
    red  orange  yellow  green  blue  indigo  violet
 0    9       3      20      6    18       8       6,
    red  orange  yellow  green  blue  indigo  violet
 0   15      13       9     18     8      11       2,
    red  orange  yellow  green  blue  indigo  violet
 0    8       2      11     13     9       3       7,
    red  orange  yellow  green  blue  indigo  violet
 0   19      11       7     16    13      15       5]

In [31]:
pd.concat(rainbows, axis = 0)

   red  orange  yellow  green  blue  indigo  violet
0    9      15      12      6    12      12       7
0    9       3      20      6    18       8       6
0   15      13       9     18     8      11       2
0    8       2      11     13     9       3       7
0   19      11       7     16    13      15       5

In [32]:
sucursal_A = pd.DataFrame({
    "Producto" : ["Laptop", "Tablet", "Smartphone"],
    "Ventas" : [25, 85, 31]
})
sucursal_B = pd.DataFrame({
    "Producto" : ["Laptop", "Tablet", "Smartphone"],
    "Ventas" : [5, 12, 78]
})
sucursal_C = pd.DataFrame({
    "Producto" : ["Laptop", "Tablet", "Smartphone"],
    "Ventas" : [14, 50, 38]
})
print(sucursal_A)
print(sucursal_B)
print(sucursal_C)

     Producto  Ventas
0      Laptop      25
1      Tablet      85
2  Smartphone      31
     Producto  Ventas
0      Laptop       5
1      Tablet      12
2  Smartphone      78
     Producto  Ventas
0      Laptop      14
1      Tablet      50
2  Smartphone      38

In [33]:
ventas = pd.concat([sucursal_A, sucursal_B, sucursal_C], keys= ["S_A", "S_B", "S_C"])
print(ventas)

         Producto  Ventas
S_A 0      Laptop      25
    1      Tablet      85
    2  Smartphone      31
S_B 0      Laptop       5
    1      Tablet      12
    2  Smartphone      78
S_C 0      Laptop      14
    1      Tablet      50
    2  Smartphone      38

In [34]:
print(ventas.loc["S_B"])

     Producto  Ventas
0      Laptop       5
1      Tablet      12
2  Smartphone      78

In [39]:
ventas.loc[[("S_A", 1), ("S_C", 2)]]

         Producto  Ventas
S_A 1      Tablet      85
S_C 2  Smartphone      38