In [1]:
import pandas as pd

# Crear el primer DataFrame
import pandas as pd

ventas = pd.DataFrame({
    "Empleado":           ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "ventas":             [120, 250, 180, 90, 310],
    "devoluciones":       [5,   12,  0,   8,  3],
    "n_clientes_nuevos":  [3,   7,   4,   1,  9],
    "dias_trabajados":    [20,  18,  22,  15, 21],
    "region":             ["Norte", "Sur", "Norte", "Sur", "Norte"]
})

metas = pd.DataFrame({
    "Empleado":           ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "meta_ventas":     [100, 300, 150, 120, 280],
    "meta_clientes":   [2,   6,   3,   1,   8],
    "bono_base":       [50,  100, 75,  60,  95],
    "meta_presencial": [18,  15,  18,  12,  20],
    "nivel":           ["junior", "senior", "medio", "junior", "senior"]
})

print("DataFrame de ventas:")
print(ventas)
print("\nDataFrame de metas:")
print(metas)

DataFrame de ventas:
  Empleado  ventas  devoluciones  n_clientes_nuevos  dias_trabajados region
0      Ana     120             5                  3               20  Norte
1     Luis     250            12                  7               18    Sur
2    María     180             0                  4               22  Norte
3    Pedro      90             8                  1               15    Sur
4    Sofía     310             3                  9               21  Norte

DataFrame de metas:
  Empleado  meta_ventas  meta_clientes  bono_base  meta_presencial   nivel
0      Ana          100              2         50               18  junior
1     Luis          300              6        100               15  senior
2    María          150              3         75               18   medio
3    Pedro          120              1         60               12  junior
4    Sofía          280              8         95               20  senior

In [2]:
# Usar la columna "Empleado" como índice en ambos DataFrames
ventas.set_index("Empleado", inplace=True)
metas.set_index("Empleado", inplace=True)
print("DataFrame de ventas:")
print(ventas)
print("\nDataFrame de metas:")
print(metas)

DataFrame de ventas:
          ventas  devoluciones  n_clientes_nuevos  dias_trabajados region
Empleado
Ana          120             5                  3               20  Norte
Luis         250            12                  7               18    Sur
María        180             0                  4               22  Norte
Pedro         90             8                  1               15    Sur
Sofía        310             3                  9               21  Norte

DataFrame de metas:
          meta_ventas  meta_clientes  bono_base  meta_presencial   nivel
Empleado
Ana               100              2         50               18  junior
Luis              300              6        100               15  senior
María             150              3         75               18   medio
Pedro             120              1         60               12  junior
Sofía             280              8         95               20  senior

In [6]:
#Unir los DataFrames usando un join
resultado = ventas.join(metas)
print("\nDataFrame unido: ")
display(resultado)

DataFrame unido:

,ventas,devoluciones,n_clientes_nuevos,dias_trabajados,region,meta_ventas,meta_clientes,bono_base,meta_presencial,nivel
Empleado,,,,,,,,,,
Ana,120,5,3,20,Norte,100,2,50,18,junior
Luis,250,12,7,18,Sur,300,6,100,15,senior
María,180,0,4,22,Norte,150,3,75,18,medio
Pedro,90,8,1,15,Sur,120,1,60,12,junior
Sofía,310,3,9,21,Norte,280,8,95,20,senior

join() es especialmente cómodo cuando la información que relaciona las tablas ya está en los índices.

## Derivar columnas de cumplimiento

In [9]:
resultado["cumplio_meta_ventas"] = resultado["ventas"] >= resultado["meta_ventas"]

resultado[["ventas", "meta_ventas", "cumplio_meta_ventas"]]

          ventas  meta_ventas  cumplio_meta_ventas
Empleado
Ana          120          100                 True
Luis         250          300                False
María        180          150                 True
Pedro         90          120                False
Sofía        310          280                 True

In [12]:
##Hacerlo para meta clientes
resultado["cumplio_meta_clientes"] = resultado["n_clientes_nuevos"] >= resultado["meta_clientes"]
#margen de devoluciones
resultado["margen_devoluciones"] = resultado["devoluciones"] / resultado["ventas"]

resultado[["ventas", "meta_ventas", "cumplio_meta_ventas",
           "n_clientes_nuevos", "cumplio_meta_clientes", "devoluciones", "margen_devoluciones"]]

,ventas,meta_ventas,cumplio_meta_ventas,n_clientes_nuevos,cumplio_meta_clientes,devoluciones,margen_devoluciones
Empleado,,,,,,,
Ana,120,100,True,3,True,5,0.041667
Luis,250,300,False,7,True,12,0.048000
María,180,150,True,4,True,0,0.000000
Pedro,90,120,False,1,True,8,0.088889
Sofía,310,280,True,9,True,3,0.009677

In [ ]:
import random
ventas_1 = pd.DataFrame({
    "ventas_lu": [random.randint(200, 500) for _ in range(5)],
    "ventas_ma": [random.randint(200, 500) for _ in range(5)],
    "ventas_mi": [random.randint(200, 500) for _ in range(5)]


}, index=["Ana", "Luis", "María", "Pedro", "Sofía"])

ventas_2 = pd.DataFrame({
    "ventas_ju": [random.randint(200, 500) for _ in range(5)],
    "ventas_vi": [random.randint(200, 500) for _ in range(5)],
    "ventas_sa": [random.randint(200, 500) for _ in range(5)]
}, index=["Ana", "Luis", "Ángel", "Adrián", "Camila"])

print(ventas_1)
print(ventas_2)

In [ ]:
# Realizar la unión utilizando join outer
ventas_Semana = ventas_1.join(ventas_2, how='outer')  # Usando 'outer' para obtener todos los índices

ventas_Semana

Crear el dataframe dos nuevamente, pero modificando el primer valor: ventas_lu, para forzar error

In [ ]:
ventas_1 = pd.DataFrame({
    "ventas_lu": [random.randint(200, 500) for _ in range(5)],
    "ventas_ma": [random.randint(200, 500) for _ in range(5)],
    "ventas_mi": [random.randint(200, 500) for _ in range(5)]


}, index=["Ana", "Luis", "María", "Pedro", "Sofía"])

ventas_2 = pd.DataFrame({
    "ventas_lu": [random.randint(200, 500) for _ in range(5)],
    "ventas_vi": [random.randint(200, 500) for _ in range(5)],
    "ventas_sa": [random.randint(200, 500) for _ in range(5)]
}, index=["Ana", "Luis", "Ángel", "Adrián", "Camila"])

print(ventas_1)
print(ventas_2)

In [ ]:
# Realizar la unión utilizando join
ventas_Semana = ventas_1.join(ventas_2, how='inner')  # Usando 'inner' para obtener la intersección de índices

ventas_Semana

Ambos DataFrames contienen una columna llamada ventas_lu.

Cuando haces join, Pandas no sabe cómo renombrar automáticamente esas columnas duplicadas.

In [ ]:
ventas_Semana = ventas_1.join(ventas_2,  lsuffix='_df1', rsuffix='_df2') 
ventas_Semana

In [ ]:
ventas_Semana= ventas_1.join(ventas_2, on = 'ventas_lu')
ventas_Semana

El método .join() está diseñado principalmente para unir por índices.

El parámetro on= se puede usar solo si el DataFrame a la izquierda (ventas_1) tiene esa columna (en este caso ventas_lu) y el DataFrame de la derecha (ventas_2) usa como índice la columna equivalente.

*Pero aquí hay dos problemas:

ventas_2 tiene como índice key, no ventas_lu.

on='ventas_mi' intenta alinear usando una columna que no corresponde al índice del otro DataFrame.

In [ ]:
ventas_reset = ventas_2.reset_index().set_index('ventas_lu')
print(ventas_reset)
ventas_Semana = ventas_1.join(ventas_reset, on='ventas_lu')
print(ventas_Semana)